[pythons]
"311" = { python_target_release = "3119", release = "2", my_release_level = "b3" }
"312" = { python_target_release = "31210", release = "2", my_release_level = "b3" }
"313" = { python_target_release = "3135", release = "1", my_release_level = "b3" }
"314" = { python_target_release = "3140", release = "1", my_release_level = "rc1" }


[[builds]]
name = "dot"
root_dir_for_builds = "C:\\Winp"
python_target = "313"
pyver = "3.13"
flavor = "test"
arch = "64"
create_installer = "7zip.zip"
preclear_build_directory = "Yes"
requirements = "C:\\Winp\\bd313\\dot_requirements.txt"
source_dirs = "C:\\Winp\\bd313\\packages.win-amd64"
find_links = "C:\\Winp\\packages.srcreq"
toolsdirs = "C:\\Winp\\bdTools\\Tools.dot"
install_options = "--no-index --pre --trusted-host=None"


[[builds]]
name = "slim"
root_dir_for_builds = "C:\\Winp"
python_target = "313"
pyver = "3.13"
flavor = "slim"
arch = "64"
create_installer = "7zip.7z"
preclear_build_directory = "Yes"
requirements = "C:\\Winp\\bd313\\requirements64_slim.txt"
source_dirs = "C:\\Winp\\bd313\\packages.win-amd64"
find_links = "C:\\Winp\\packages.srcreq"
toolsdirs = "C:\\Winp\\bdTools\\tools64_pandoc_alone"
install_options = "--no-index --pre --trusted-host=None" 


[[builds]]
name = "whl"
root_dir_for_builds = "C:\\Winp"
python_target = "313"
pyver = "3.13"
flavor = "whl"
arch = "64"
create_installer = ".7z-mx9"
preclear_build_directory = "Yes"
requirements = "C:\\Winp\\bd313\\dot_requirements.txt"
source_dirs = "C:\\Winp\\bd313\\packages.win-amd64"
find_links = "C:\\Winp\\packages.srcreq"
toolsdirs = "C:\\Winp\\bdTools\\Tools.dot"
install_options = "--no-index --pre --trusted-host=None"
wheelhousereq = "C:\\Winp\\bd313\\requirements64_whl.txt"
