[pythons]
"311" = { python_target_release = "3119", release = "2", my_release_level = "b3" }
"312" = { python_target_release = "31210", release = "2", my_release_level = "b3" }
"313" = { python_target_release = "3135", release = "1", my_release_level = "b3" }
"314" = { python_target_release = "3140", release = "1", my_release_level = "rc1b" }


[[builds]]
name = "dot"
root_dir_for_builds = "C:\\Winp"
python_target = "314"
pyver = "3.14"
flavor = "dot"
arch = "64"
create_installer = "7zip.zip"
preclear_build_directory = "Yes"
requirements = "C:\\Winp\\bd314\\dot_requirements.txt"
source_dirs = "C:\\Winp\\bd314\\packages.win-amd64"
find_links = "C:\\Winp\\packages.srcreq"
toolsdirs = "C:\\Winp\\bdTools\\Tools.dot"
install_options = "--no-index --pre --trusted-host=None"


[[builds]]
name = "free"
root_dir_for_builds = "C:\\Winp"
python_target = "314"
pyver = "3.14"
flavor = "free"
arch = "64"
create_installer = "7zip.zip"
preclear_build_directory = "Yes"
requirements = "C:\\Winp\\bd314\\dot_requirements.txt"
source_dirs = "C:\\Winp\\bd314\\packages.win-amd64t"
find_links = "C:\\Winp\\packages.srcreq"
toolsdirs = "C:\\Winp\\bdTools\\Tools.dot"
install_options = "--no-index --pre --trusted-host=None"

