name: Build WinPython Dot 3.13, # fix to build #3

on:
  workflow_dispatch:

jobs:
  build-dot:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download python-3.13 standalone
        shell: pwsh
        run: |
          $url = "https://github.com/indygreg/python-build-standalone/releases/download/20240421/cpython-3.13.0b1+20240421-x86_64-pc-windows-msvc-shared-install_only.zip"
          $output = "python-3.13-embed.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Get-Item $output | Format-List Name,Length,LastWriteTime
          Start-Sleep -Seconds 2
          New-Item -ItemType Directory -Path dotpython
          Expand-Archive -Path $output -DestinationPath dotpython

      - name: List dotpython contents (for debugging)
        shell: pwsh
        run: |
          Get-ChildItem -Recurse dotpython

      - name: Prepare WinPython dot structure
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path WinPython-dot-3.13
          # Get-ChildItem dotpython | Move-Item -Destination WinPython-dot-3.13
          # fix: Usually, indygreg zips extract all files directly into the target, not into a subfolder: dotpython/python.exe, dotpython/Lib, etc.
          Get-ChildItem -Path dotpython -Force | Move-Item -Destination WinPython-dot-3.13 -Force
          # Add more WinPython-specific folders/files here if needed

      - name: List WinPython-dot-3.13 contents (for debugging)
        shell: pwsh
        run: |
          Get-ChildItem -Recurse WinPython-dot-3.13
      - name: Zip the result
        # run: |
        #  Compress-Archive -Path WinPython-dot-3.13\* -DestinationPath WinPython-dot-3.13.zip
        shell: pwsh
        run: |
          Compress-Archive -Path WinPython-dot-3.13\* -DestinationPath WinPython-dot-3.13.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinPython-dot-3.13
          path: WinPython-dot-3.13.zip