name: Build WinPython Dot 3.13

on:
  workflow_dispatch:

jobs:
  build-dot:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download python-3.13 standalone
        run: |
          curl -L -o python-3.13-embed.zip https://github.com/indygreg/python-build-standalone/releases/download/20240421/cpython-3.13.0b1+20240421-x86_64-pc-windows-msvc-shared-install_only.zip
          mkdir dotpython
          powershell -Command "Expand-Archive -Path 'python-3.13-embed.zip' -DestinationPath 'dotpython'"
      - name: Prepare WinPython dot structure
        run: |
          mkdir WinPython-dot-3.13
          move dotpython\* WinPython-dot-3.13\
          # Add more WinPython-specific folders/files here if needed

      - name: Zip the result
        run: |
          Compress-Archive -Path WinPython-dot-3.13\* -DestinationPath WinPython-dot-3.13.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinPython-dot-3.13
          path: WinPython-dot-3.13.zip